"""Train a SegFormer rail-edge detector on prepared RAIL-BENCH heatmaps.

Input data is generated by scripts/prepare_railbench_rail.py. The detector
predicts two heatmap channels: left rail edge and right rail edge.

Example:
    python scripts/train_rail_detector.py \
        --data /autodl-fs/data/GigaSLAM/railbench/object_and_rail/prepared_rail \
        --out /autodl-fs/data/GigaSLAM/railbench/rail_detector_runs/segformer_b0 \
        --epochs 30 \
        --batch-size 4 \
        --image-size 768 432 \
        --device cuda
"""

import argparse
import csv
import json
import os
import random
import sys
import time
from pathlib import Path

import cv2
import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from utils.rail_detector_model import (  # noqa: E402
    build_segformer_rail_detector,
    rail_heatmap_loss,
    rail_heatmap_metrics,
)


IMAGENET_MEAN = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
IMAGENET_STD = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)


def parse_args():
    parser = argparse.ArgumentParser(description="Train SegFormer rail-edge detector.")
    parser.add_argument("--data", required=True, help="prepared_rail directory.")
    parser.add_argument("--out", required=True, help="Run output directory.")
    parser.add_argument("--model-name", default="nvidia/segformer-b0-finetuned-ade-512-512")
    parser.add_argument("--no-pretrained", action="store_true", help="Initialize SegFormer from config instead of pretrained weights.")
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--image-size", nargs=2, type=int, default=[768, 432], metavar=("W", "H"))
    parser.add_argument("--dice-weight", type=float, default=1.0)
    parser.add_argument("--threshold", type=float, default=0.3)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--amp", action="store_true", help="Use CUDA autocast mixed precision.")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--preview-count", type=int, default=12)
    parser.add_argument("--save-every", type=int, default=5)
    parser.add_argument("--max-train", type=int, default=0, help="Debug limit; 0 means all.")
    parser.add_argument("--max-val", type=int, default=0, help="Debug limit; 0 means all.")
    return parser.parse_args()


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


class PreparedRailDataset(Dataset):
    def __init__(self, root, split, image_size=(768, 432), max_items=0):
        self.root = Path(root)
        self.split = split
        self.split_dir = self.root / split
        self.image_size = tuple(image_size)
        manifest = self.split_dir / "manifest.csv"
        if not manifest.exists():
            raise FileNotFoundError(f"Manifest not found: {manifest}")
        with open(manifest, newline="", encoding="utf-8") as f:
            self.rows = list(csv.DictReader(f))
        if max_items:
            self.rows = self.rows[:max_items]

    def __len__(self):
        return len(self.rows)

    def _read_rgb(self, rel_path):
        path = self.split_dir / rel_path
        image = cv2.imread(str(path), cv2.IMREAD_COLOR)
        if image is None:
            raise FileNotFoundError(f"Failed to read image: {path}")
        return cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    def _read_gray(self, rel_path):
        path = self.split_dir / rel_path
        image = cv2.imread(str(path), cv2.IMREAD_GRAYSCALE)
        if image is None:
            raise FileNotFoundError(f"Failed to read mask: {path}")
        return image

    def __getitem__(self, idx):
        row = self.rows[idx]
        out_w, out_h = self.image_size
        image = self._read_rgb(row["image"])
        left = self._read_gray(row["left_heatmap"])
        right = self._read_gray(row["right_heatmap"])
        ignore = self._read_gray(row["ignore_mask"])

        if image.shape[1] != out_w or image.shape[0] != out_h:
            image = cv2.resize(image, (out_w, out_h), interpolation=cv2.INTER_AREA)
            left = cv2.resize(left, (out_w, out_h), interpolation=cv2.INTER_LINEAR)
            right = cv2.resize(right, (out_w, out_h), interpolation=cv2.INTER_LINEAR)
            ignore = cv2.resize(ignore, (out_w, out_h), interpolation=cv2.INTER_NEAREST)

        image_t = torch.from_numpy(image).float().permute(2, 0, 1) / 255.0
        image_t = (image_t - IMAGENET_MEAN) / IMAGENET_STD
        target = np.stack([left, right], axis=0).astype(np.float32) / 255.0
        target_t = torch.from_numpy(target).clamp(0.0, 1.0)
        valid_t = 1.0 - (torch.from_numpy(ignore.astype(np.float32))[None] / 255.0).clamp(0.0, 1.0)
        return {
            "pixel_values": image_t,
            "target": target_t,
            "valid": valid_t,
            "file_name": row["file_name"],
        }


def collate_fn(batch):
    return {
        "pixel_values": torch.stack([b["pixel_values"] for b in batch]),
        "target": torch.stack([b["target"] for b in batch]),
        "valid": torch.stack([b["valid"] for b in batch]),
        "file_name": [b["file_name"] for b in batch],
    }


def save_checkpoint(path, model, optimizer, epoch, metrics, args):
    payload = {
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "epoch": epoch,
        "metrics": metrics,
        "args": vars(args),
    }
    torch.save(payload, path)


def overlay_heatmaps(image_norm, target, pred):
    image = image_norm.cpu() * IMAGENET_STD + IMAGENET_MEAN
    image = (image.clamp(0, 1).permute(1, 2, 0).numpy() * 255).astype(np.uint8)
    target_rgb = _heatmap_to_rgb(target.cpu().numpy())
    pred_rgb = _heatmap_to_rgb(pred.cpu().numpy())
    return np.concatenate([image, target_rgb, pred_rgb], axis=1)


def _heatmap_to_rgb(two_ch):
    left = np.clip(two_ch[0], 0, 1)
    right = np.clip(two_ch[1], 0, 1)
    rgb = np.zeros((left.shape[0], left.shape[1], 3), dtype=np.uint8)
    rgb[..., 0] = (left * 255).astype(np.uint8)
    rgb[..., 1] = (right * 255).astype(np.uint8)
    return rgb


@torch.no_grad()
def evaluate(model, loader, device, args, preview_dir=None):
    model.eval()
    total_loss = 0.0
    total_bce = 0.0
    total_dice = 0.0
    total_iou = 0.0
    total_iou_left = 0.0
    total_iou_right = 0.0
    n = 0
    preview_saved = 0
    if preview_dir:
        preview_dir.mkdir(parents=True, exist_ok=True)

    for batch in tqdm(loader, desc="val", leave=False):
        pixel_values = batch["pixel_values"].to(device, non_blocking=True)
        target = batch["target"].to(device, non_blocking=True)
        valid = batch["valid"].to(device, non_blocking=True)
        logits = model(pixel_values=pixel_values).logits
        loss, parts = rail_heatmap_loss(logits, target, valid, dice_weight=args.dice_weight)
        metrics = rail_heatmap_metrics(logits, target, valid, threshold=args.threshold)

        bs = pixel_values.shape[0]
        total_loss += float(loss.detach().cpu()) * bs
        total_bce += parts["bce"] * bs
        total_dice += parts["dice"] * bs
        total_iou += metrics["iou_mean"] * bs
        total_iou_left += metrics["iou_left"] * bs
        total_iou_right += metrics["iou_right"] * bs
        n += bs

        if preview_dir and preview_saved < args.preview_count:
            logits_up = torch.nn.functional.interpolate(
                logits,
                size=target.shape[-2:],
                mode="bilinear",
                align_corners=False,
            )
            probs = torch.sigmoid(logits_up)
            for i in range(min(bs, args.preview_count - preview_saved)):
                panel = overlay_heatmaps(pixel_values[i].cpu(), target[i].cpu(), probs[i].cpu())
                out_path = preview_dir / f"{preview_saved:03d}_{batch['file_name'][i]}"
                cv2.imwrite(str(out_path), cv2.cvtColor(panel, cv2.COLOR_RGB2BGR))
                preview_saved += 1

    denom = max(n, 1)
    return {
        "loss": total_loss / denom,
        "bce": total_bce / denom,
        "dice": total_dice / denom,
        "iou_mean": total_iou / denom,
        "iou_left": total_iou_left / denom,
        "iou_right": total_iou_right / denom,
    }


def train_one_epoch(model, loader, optimizer, scaler, device, args, epoch):
    model.train()
    total = 0.0
    n = 0
    progress = tqdm(loader, desc=f"train {epoch}", leave=False)
    for batch in progress:
        pixel_values = batch["pixel_values"].to(device, non_blocking=True)
        target = batch["target"].to(device, non_blocking=True)
        valid = batch["valid"].to(device, non_blocking=True)
        optimizer.zero_grad(set_to_none=True)
        use_amp = args.amp and device.type == "cuda"
        with torch.autocast(device_type="cuda", dtype=torch.float16, enabled=use_amp):
            logits = model(pixel_values=pixel_values).logits
            loss, parts = rail_heatmap_loss(logits, target, valid, dice_weight=args.dice_weight)
        if scaler is not None and use_amp:
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            optimizer.step()
        bs = pixel_values.shape[0]
        total += float(loss.detach().cpu()) * bs
        n += bs
        progress.set_postfix(loss=total / max(n, 1), bce=parts["bce"], dice=parts["dice"])
    return total / max(n, 1)


def main():
    args = parse_args()
    set_seed(args.seed)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    with open(out_dir / "args.json", "w", encoding="utf-8") as f:
        json.dump(vars(args), f, indent=2)

    device = torch.device(args.device if torch.cuda.is_available() or args.device == "cpu" else "cpu")
    train_set = PreparedRailDataset(args.data, "train", image_size=args.image_size, max_items=args.max_train)
    val_set = PreparedRailDataset(args.data, "val", image_size=args.image_size, max_items=args.max_val)
    train_loader = DataLoader(
        train_set,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=device.type == "cuda",
        collate_fn=collate_fn,
        drop_last=False,
    )
    val_loader = DataLoader(
        val_set,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=device.type == "cuda",
        collate_fn=collate_fn,
        drop_last=False,
    )

    model = build_segformer_rail_detector(
        model_name=args.model_name,
        num_channels=2,
        pretrained=not args.no_pretrained,
    ).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scaler = torch.cuda.amp.GradScaler(enabled=args.amp and device.type == "cuda")

    best_loss = float("inf")
    history = []
    start = time.time()
    for epoch in range(1, args.epochs + 1):
        train_loss = train_one_epoch(model, train_loader, optimizer, scaler, device, args, epoch)
        preview_dir = out_dir / "val_preview" / f"epoch_{epoch:03d}"
        val_metrics = evaluate(model, val_loader, device, args, preview_dir=preview_dir)
        record = {"epoch": epoch, "train_loss": train_loss, **{f"val_{k}": v for k, v in val_metrics.items()}}
        history.append(record)
        print(
            f"[rail-detector] epoch={epoch:03d} train_loss={train_loss:.4f} "
            f"val_loss={val_metrics['loss']:.4f} val_iou={val_metrics['iou_mean']:.4f}"
        )

        save_checkpoint(out_dir / "last.pt", model, optimizer, epoch, record, args)
        if val_metrics["loss"] < best_loss:
            best_loss = val_metrics["loss"]
            save_checkpoint(out_dir / "best.pt", model, optimizer, epoch, record, args)
        if args.save_every > 0 and epoch % args.save_every == 0:
            save_checkpoint(out_dir / f"epoch_{epoch:03d}.pt", model, optimizer, epoch, record, args)

        with open(out_dir / "metrics.json", "w", encoding="utf-8") as f:
            json.dump({"history": history, "best_loss": best_loss, "elapsed_sec": time.time() - start}, f, indent=2)

    print(f"[rail-detector] done. best_loss={best_loss:.4f}, out={out_dir}")


if __name__ == "__main__":
    main()
