"""Train a TEP-style ego-path regression model without W&B.

This wrapper reuses the open-source train-ego-path-detection model/loss code,
but keeps the GigaSLAM train/val split explicit and writes local artifacts only.
It expects annotation JSON files generated by prepare_railbench_ego_path.py.
"""

import argparse
import json
import os
import random
import sys
import time
from pathlib import Path

import cv2
import numpy as np
import torch
import yaml
from PIL import Image
from torch.utils.data import DataLoader


def parse_args():
    parser = argparse.ArgumentParser(description="Train EgoPath regression detector.")
    parser.add_argument("--tep-root", required=True, help="Path to train-ego-path-detection repo.")
    parser.add_argument("--train-images", required=True)
    parser.add_argument("--train-annotations", required=True)
    parser.add_argument("--val-images", required=True)
    parser.add_argument("--val-annotations", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--backbone", default="resnet18", choices=["resnet18", "resnet34", "resnet50", "efficientnet-b0", "efficientnet-b1", "efficientnet-b2", "efficientnet-b3"])
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--epochs", type=int, default=120)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--optimizer", default="adam", choices=["adam"])
    parser.add_argument("--scheduler", default="one_cycle", choices=["one_cycle", "none"])
    parser.add_argument("--weight-decay", type=float, default=0.0)
    parser.add_argument("--input-size", nargs=2, type=int, default=[512, 512], metavar=("W", "H"))
    parser.add_argument("--anchors", type=int, default=64)
    parser.add_argument("--pool-channels", type=int, default=8)
    parser.add_argument("--fc-hidden-size", type=int, default=2048)
    parser.add_argument("--ylimit-loss-weight", type=float, default=0.5)
    parser.add_argument("--perspective-weight-limit-percentile", type=float, default=95.0)
    parser.add_argument("--no-perspective-weight-limit", action="store_true")
    parser.add_argument("--no-pretrained", action="store_true")
    parser.add_argument("--brightness", type=float, default=0.5)
    parser.add_argument("--contrast", type=float, default=0.5)
    parser.add_argument("--saturation", type=float, default=0.5)
    parser.add_argument("--hue", type=float, default=0.2)
    parser.add_argument("--crop-margin-sides", type=float, default=0.1)
    parser.add_argument("--crop-margin-top", type=float, default=0.1)
    parser.add_argument("--std-dev-factor-sides", type=float, default=0.3)
    parser.add_argument("--std-dev-factor-top", type=float, default=0.1)
    parser.add_argument("--val-iterations", type=int, default=1)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--save-every", type=int, default=10)
    parser.add_argument("--preview-count", type=int, default=24)
    parser.add_argument("--max-train", type=int, default=0)
    parser.add_argument("--max-val", type=int, default=0)
    parser.add_argument("--amp", action="store_true")
    return parser.parse_args()


def import_tep(tep_root):
    tep_root = str(Path(tep_root).resolve())
    if tep_root not in sys.path:
        sys.path.insert(0, tep_root)
    from src.nn.loss import TrainEgoPathRegressionLoss
    from src.nn.model import RegressionNet
    from src.utils.dataset import PathsDataset
    from src.utils.postprocessing import regression_to_rails

    return PathsDataset, RegressionNet, TrainEgoPathRegressionLoss, regression_to_rails


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def make_rgb_paths_dataset_class(base_cls):
    class RGBPathsDataset(base_cls):
        def __getitem__(self, idx):
            if self.method != "regression":
                raise NotImplementedError("train_ego_path_detector.py only supports regression datasets")
            img_name = self.imgs[idx]
            img = Image.open(os.path.join(self.imgs_path, img_name)).convert("RGB")
            annotation = self.annotations[img_name]
            rails_mask = self.generate_rails_mask(img.size, annotation)
            img, rails_mask = self.random_crop(img, rails_mask)
            img, rails_mask = self.random_flip_lr(img, rails_mask)
            if self.to_tensor:
                img = self.to_tensor(img)
            if self.img_aug:
                img = self.img_aug(img)
            path_gt, ylim_gt = self.generate_target_regression(rails_mask)
            if self.to_tensor:
                path_gt = torch.from_numpy(path_gt)
                ylim_gt = torch.tensor(ylim_gt)
            return img, path_gt, ylim_gt

    return RGBPathsDataset


def load_annotation_count(path):
    with open(path, "r", encoding="utf-8") as f:
        return len(json.load(f))


def build_config(args):
    width, height = [int(v) for v in args.input_size]
    percentile = None if args.no_perspective_weight_limit else float(args.perspective_weight_limit_percentile)
    return {
        "method": "regression",
        "backbone": args.backbone,
        "pretrained": not args.no_pretrained,
        "input_shape": [3, height, width],
        "optimizer": args.optimizer,
        "scheduler": None if args.scheduler == "none" else args.scheduler,
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "learning_rate": args.lr,
        "weight_decay": args.weight_decay,
        "workers": args.num_workers,
        "seed": args.seed,
        "anchors": args.anchors,
        "pool_channels": args.pool_channels,
        "fc_hidden_size": args.fc_hidden_size,
        "ylimit_loss_weight": args.ylimit_loss_weight,
        "perspective_weight_limit_percentile": percentile,
        "brightness": args.brightness,
        "contrast": args.contrast,
        "saturation": args.saturation,
        "hue": args.hue,
        "crop_margin_sides": args.crop_margin_sides,
        "crop_margin_top": args.crop_margin_top,
        "std_dev_factor_sides": args.std_dev_factor_sides,
        "std_dev_factor_top": args.std_dev_factor_top,
        "train_images": str(Path(args.train_images).resolve()),
        "train_annotations": str(Path(args.train_annotations).resolve()),
        "val_images": str(Path(args.val_images).resolve()),
        "val_annotations": str(Path(args.val_annotations).resolve()),
        "tep_root": str(Path(args.tep_root).resolve()),
    }


class ConsoleLogger:
    def info(self, msg):
        print(msg, flush=True)


def make_dataset(PathsDataset, images_path, annotations_path, config, img_aug, max_items):
    n = load_annotation_count(annotations_path)
    indices = list(range(n))
    if max_items:
        indices = indices[:max_items]
    return PathsDataset(
        imgs_path=images_path,
        annotations_path=annotations_path,
        indices=indices,
        config=config,
        method="regression",
        img_aug=img_aug,
        to_tensor=True,
    )


def target_to_device(target, device):
    return [target[0].to(device), target[1].to(device)]


def train_one_epoch(model, loader, criterion, optimizer, device, amp):
    model.train()
    total_loss = 0.0
    total_items = 0
    scaler = torch.cuda.amp.GradScaler(enabled=amp and device.type == "cuda")
    for data, path_gt, ylim_gt in loader:
        data = data.to(device, non_blocking=True)
        target = [path_gt.to(device, non_blocking=True), ylim_gt.to(device, non_blocking=True)]
        optimizer.zero_grad(set_to_none=True)
        with torch.cuda.amp.autocast(enabled=amp and device.type == "cuda"):
            output = model(data)
            loss = criterion(output, target)
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        bs = data.shape[0]
        total_loss += float(loss.detach().cpu()) * bs
        total_items += bs
    return total_loss / max(total_items, 1)


@torch.no_grad()
def evaluate(model, loader, criterion, regression_to_rails, device):
    model.eval()
    total_loss = 0.0
    total_items = 0
    ious = []
    for data, path_gt, ylim_gt in loader:
        data = data.to(device, non_blocking=True)
        target = [path_gt.to(device, non_blocking=True), ylim_gt.to(device, non_blocking=True)]
        output = model(data)
        loss = criterion(output, target)
        bs = data.shape[0]
        total_loss += float(loss.detach().cpu()) * bs
        total_items += bs
        ious.extend(batch_iou(output, path_gt, ylim_gt, regression_to_rails, data.shape[-2:]))
    return {
        "loss": total_loss / max(total_items, 1),
        "iou": float(np.mean(ious)) if ious else 0.0,
    }


def batch_iou(output, path_gt, ylim_gt, regression_to_rails, image_hw):
    out = output.detach().cpu()
    path_gt = path_gt.detach().cpu()
    ylim_gt = ylim_gt.detach().cpu()
    h, w = int(image_hw[0]), int(image_hw[1])
    ious = []
    for i in range(out.shape[0]):
        pred_traj = out[i, :-1].reshape(2, path_gt.shape[-1]).numpy()
        pred_ylim = float(torch.sigmoid(out[i, -1]).item())
        gt_traj = path_gt[i].numpy()
        gt_ylim = float(ylim_gt[i].item())
        pred_rails = regression_to_rails(pred_traj, pred_ylim)
        gt_rails = regression_to_rails(gt_traj, gt_ylim)
        pred_mask = rails_to_mask(pred_rails, w, h)
        gt_mask = rails_to_mask(gt_rails, w, h)
        inter = np.logical_and(pred_mask, gt_mask).sum()
        union = np.logical_or(pred_mask, gt_mask).sum()
        ious.append(float(inter / union) if union > 0 else 0.0)
    return ious


def rails_to_mask(rails, width, height):
    mask = np.zeros((height, width), dtype=np.uint8)
    if rails is None or len(rails) != 2 or len(rails[0]) < 2 or len(rails[1]) < 2:
        return mask.astype(bool)
    left = np.asarray(rails[0], dtype=np.float32)
    right = np.asarray(rails[1], dtype=np.float32)
    pts = np.concatenate([left, right[::-1]], axis=0)
    pts[:, 0] = np.clip(pts[:, 0] * (width - 1), 0, width - 1)
    pts[:, 1] = np.clip(pts[:, 1] * (height - 1), 0, height - 1)
    cv2.fillPoly(mask, [np.round(pts).astype(np.int32)], 1)
    return mask.astype(bool)


def save_previews(model, dataset, regression_to_rails, out_dir, device, count):
    if count <= 0:
        return
    out_dir.mkdir(parents=True, exist_ok=True)
    model.eval()
    n = min(count, len(dataset))
    with torch.no_grad():
        for idx in range(n):
            image_t, path_gt, ylim_gt = dataset[idx]
            tensor = image_t.unsqueeze(0).to(device)
            output = model(tensor).detach().cpu()[0]
            pred_traj = output[:-1].reshape(2, path_gt.shape[-1]).numpy()
            pred_ylim = float(torch.sigmoid(output[-1]).item())
            gt_rails = regression_to_rails(path_gt.numpy(), float(ylim_gt.item()))
            pred_rails = regression_to_rails(pred_traj, pred_ylim)
            image = (image_t.permute(1, 2, 0).cpu().numpy().clip(0, 1) * 255).astype(np.uint8)
            vis = draw_rails(image, gt_rails, (0, 255, 0), 2)
            vis = draw_rails(vis, pred_rails, (255, 0, 0), 2)
            name = getattr(dataset, "imgs", [f"{idx:05d}.png"])[idx]
            out_path = out_dir / f"{idx:03d}_{Path(name).stem}.jpg"
            cv2.imwrite(str(out_path), cv2.cvtColor(vis, cv2.COLOR_RGB2BGR))


def draw_rails(image_rgb, rails, color_rgb, thickness):
    vis = image_rgb.copy()
    h, w = vis.shape[:2]
    if rails is None:
        return vis
    for rail in rails:
        pts = np.asarray(rail, dtype=np.float32)
        if pts.shape[0] < 2:
            continue
        pts[:, 0] = np.clip(pts[:, 0] * (w - 1), 0, w - 1)
        pts[:, 1] = np.clip(pts[:, 1] * (h - 1), 0, h - 1)
        cv2.polylines(vis, [np.round(pts).astype(np.int32)], False, color_rgb, thickness, lineType=cv2.LINE_AA)
    return vis


def save_metrics(path, rows):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(rows, f, indent=2)


def main():
    args = parse_args()
    PathsDataset, RegressionNet, TrainEgoPathRegressionLoss, regression_to_rails = import_tep(args.tep_root)
    PathsDataset = make_rgb_paths_dataset_class(PathsDataset)
    set_seed(args.seed)
    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    config = build_config(args)
    with open(out_dir / "config.yaml", "w", encoding="utf-8") as f:
        yaml.safe_dump(config, f, sort_keys=False)
    with open(out_dir / "args.json", "w", encoding="utf-8") as f:
        json.dump(vars(args), f, indent=2)

    train_dataset = make_dataset(
        PathsDataset, args.train_images, args.train_annotations, config,
        img_aug=True, max_items=args.max_train,
    )
    val_dataset = make_dataset(
        PathsDataset, args.val_images, args.val_annotations, config,
        img_aug=False, max_items=args.max_val,
    )
    train_loader = DataLoader(
        train_dataset,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=True,
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=True,
    )

    device = torch.device(args.device if args.device != "cuda" or torch.cuda.is_available() else "cpu")
    model = RegressionNet(
        backbone=args.backbone,
        input_shape=tuple(config["input_shape"]),
        anchors=args.anchors,
        pool_channels=args.pool_channels,
        fc_hidden_size=args.fc_hidden_size,
        pretrained=not args.no_pretrained,
    ).to(device)
    criterion = TrainEgoPathRegressionLoss(
        ylimit_loss_weight=args.ylimit_loss_weight,
        perspective_weight_limit=(
            train_dataset.get_perspective_weight_limit(
                percentile=float(args.perspective_weight_limit_percentile),
                logger=ConsoleLogger(),
            )
            if not args.no_perspective_weight_limit
            else None
        ),
    )
    set_seed(args.seed)
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scheduler = None
    if args.scheduler == "one_cycle" and args.epochs > 0:
        scheduler = torch.optim.lr_scheduler.OneCycleLR(
            optimizer=optimizer,
            max_lr=args.lr,
            total_steps=args.epochs,
            pct_start=0.1,
        )

    metrics = []
    best_val_loss = float("inf")
    best_epoch = -1
    for epoch in range(1, args.epochs + 1):
        start = time.time()
        train_loss = train_one_epoch(model, train_loader, criterion, optimizer, device, args.amp)
        val_accum = {"loss": 0.0, "iou": 0.0}
        val_iters = max(int(args.val_iterations), 1)
        for _ in range(val_iters):
            val_metrics = evaluate(model, val_loader, criterion, regression_to_rails, device)
            val_accum["loss"] += val_metrics["loss"]
            val_accum["iou"] += val_metrics["iou"]
        val_loss = val_accum["loss"] / val_iters
        val_iou = val_accum["iou"] / val_iters
        if scheduler is not None:
            scheduler.step()

        row = {
            "epoch": epoch,
            "train_loss": train_loss,
            "val_loss": val_loss,
            "val_iou": val_iou,
            "lr": optimizer.param_groups[0]["lr"],
            "seconds": time.time() - start,
        }
        metrics.append(row)
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_epoch = epoch
            torch.save(model.state_dict(), out_dir / "best.pt")
        if args.save_every > 0 and epoch % args.save_every == 0:
            torch.save(model.state_dict(), out_dir / f"epoch_{epoch:03d}.pt")
        torch.save(model.state_dict(), out_dir / "last.pt")
        save_metrics(out_dir / "metrics.json", metrics)
        print(
            f"{time.strftime('%Y-%m-%d %H:%M:%S')} | epoch {epoch:03d}/{args.epochs:03d} "
            f"| train={train_loss:.5f} | val={val_loss:.5f} | iou={val_iou:.4f} "
            f"| best={best_val_loss:.5f}@{best_epoch}",
            flush=True,
        )

    if args.epochs == 0:
        torch.save(model.state_dict(), out_dir / "best.pt")
        torch.save(model.state_dict(), out_dir / "last.pt")
    save_previews(model, val_dataset, regression_to_rails, out_dir / "preview", device, args.preview_count)
    print(f"[ego-path-train] done: {out_dir}")


if __name__ == "__main__":
    main()
