inherit_from: configs/railway/rowtrack350/scenes/scene_13_train.yaml

Results:
  save_dir: results/RailScale_ablation

RailScale:
  enabled: false
  apply_correction: false
  log_diag: false
  log_row_diag: false
  save_debug: false
