inherit_from: configs/railway/rowtrack350/template.yaml

Dataset:
  color_path: /home/leizongru/lzr_ws/railway_data/scene_05_train
  pose_path: /home/leizongru/lzr_ws/railway_data/gt_poses/npy/scene_05_train.npy
